swagger: '2.0'
info:
  title: APIRecintos
  description:  API para prestação de informações sobre eventos de controle aduaneiro a cargo dos Redex, Recintos, Operadores Portuários e demais intervenientes em carga sobre controle aduaneiro.
  version: '0.9'
consumes:
  - application/json
produces:
  - application/json
definitions:
  Evento:
    type: object
    properties:
      IDEvento:
        type: integer
        description: ID do Evento no sistema original, para referencia e consulta
      dataevento:
        type: string
        format: date-time
        description: Data de ocorrência física do evento
      operadorevento:
        type: string
        description: CPF do Operador que realizou o evento fisicamente/presencialmente
      dataregistro:
        type: string
        format: date-time
        description: Data de registro do evento no Sistema
      operadorregistro:
        type: string
        description: CPF do Operador que registrou o evento no Sistema
  EntradaSaida:
    type: string
    enum:
      - Entrada
      - Saida
    description: Operação de entrada ou de saída de carga
  Autoridade:
    type: string
    enum:
      - RFB
      - MAPA
    description: Sigla da autoridade
  CredenciamentoPessoa:
    allOf:
      - $ref: '#/definitions/Evento'
      - type: object
        properties:
          nome:
            type: string
            description: Nome da Pessoa credenciada
          cpf:
            type: string
            description: CPF da Pessoa credenciada
          cnh:
            type: string
            description: Numero do CNH (para motoristas)
          identidade:
            type: string
            description: RG ou Identidade do estrangeiro
          datanascimento:
            type: string
            format: date
            description: Data de nascimento
          representado:
            type: string
            description: CNPJ/CPF representado
          nomerepresentado:
            type: string
            description: Nome representado
          funcao:
            type: string
            description: Função na empresa representada
          iniciovalidade:
            type: string
            format: date-time
            description: Início Período de validade do credenciamento
          fimvalidade:
            type: string
            format: date-time
            description: Fim Período de validade do credenciamento
          permissao:
            type: string
            description: Areas permitidas acesso
          materiais:
            type: string
            description: Lista materiais/ferramentas de trabalho
          motivacao:
            type: string
            description: Motivacao de acesso ao terminal
  AcessoPessoa:
    allOf:
      - $ref: '#/definitions/Evento'
      - type: object
        properties:
          cpf:
            type: string
            description: CPF da Pessoa credenciada
          identidade:
            type: string
            description: RG ou Identidade do estrangeiro
          formaidentificacao:
            type: string
            description: Identificação (cartão-C, biométrico-B, facial-F ou manual-M)
          portaoacesso:
            type: string
            description: Codigo do portao utilizado para entrada
  CredenciamentoVeiculo:
    allOf:
      - $ref: '#/definitions/Evento'
      - type: object
        properties:
          placa:
            type: string
            description: Placa Cavalo-trator/truck/automóvel
          marca:
            type: string
            description: Marca
          modelo:
            type: string
            description: Modelo
          ano:
            type: string
            description: Ano
          iniciovalidade:
            type: string
            format: date-time
            description: Início Período de validade do credenciamento
          fimvalidade:
            type: string
            format: date-time
            description: Fim Período de validade do credenciamento
          permissao:
            type: string
            description: Areas permitidas acesso
          geolocalizacao:
            type: boolean
            description: Verdadeiro para veículo com monitoramento de posição via satélite ou similar
  AgendamentoVeiculo:
    allOf:
      - $ref: '#/definitions/Evento'
      - type: object
        properties:
          Placa:
            type: string
            description: Placa Cavalo-trator/truck/automóvel
          tipooperacao:
            $ref: '#/definitions/EntradaSaida'
          reboques:
            type: array
            items:
              type: object
              properties:
                placa:
                  type: string
                vazio:
                  type: boolean
          containers:
            type: array
            items:
              type: object
              properties:
                numero:
                  type: string
                vazio:
                  type: boolean
          manifesto:
            type: string
            description: Manifesto
          cpfcnpjtransportador:
            type: string
            description: CPF ou CNPJ do Transportador responsável
          nometransportador:
            type: string
            description: Nome do Transportador responsável
          cpfmotorista:
            type: string
            description: CPF do Motorista
          nomemotorista:
            type: string
            description: Nome do Motorista
          cpfcnpjcliente:
            type: string
            description: CPF ou CNPJ do Cliente
          nomecliente:
            type: string
            description: Nome Cliente
          dataagendamento:
            type: string
            format: date-time
            description: Data e Hora agendada
          paisdestino:
            type: string
            description: Pais destino da carga
          navioembarque:
            type: string
            description: Navio de embarque programado
  AcessoVeiculo:
    allOf:
      - $ref: '#/definitions/Evento'
      - type: object
        properties:
          IDAgendamento:
            type: integer
            description: ID do Agendamento desta operação, se houver
          IDGate:
            type: string
            description: Identificador do Portao de ocorrencia do Evento
          placa:
            type: string
            description: Placa Cavalo-trator/truck/automóvel
          Chassi:
            type: string
            description: Chassi do veículo em caso do veículo ser a carga
          tipooperacao:
            $ref: '#/definitions/EntradaSaida'
          reboques:
            type: array
            items:
              type: object
              properties:
                placa:
                  type: string
                vazio:
                  type: boolean
                lacres:
                  type: string
                avarias:
                  type: string
          conteineres:
            type: array
            items:
              type: object
              properties:
                numero:
                  type: string
                vazio:
                  type: boolean
                lacres:
                  type: string
                avarias:
                  type: string
          CTE:
            type: string
            description: CTE Conhecimento de Transporte Eletrônico)
          DTC:
            type: string
            description: DTC (Declaração de Trânsito de Contêiner)
          manifesto:
            type: string
            description: Manifesto
          cpfcnpjtransportador:
            type: string
            description: CPF ou CNPJ do Transportador responsável
          nometransportador:
            type: string
            description: Nome do Transportador responsável
          cpfmotorista:
            type: string
            description: CPF do Motorista
          nomemotorista:
            type: string
            description: Nome do Motorista
          cpfcnpjcliente:
            type: string
            description: CPF ou CNPJ do Cliente
          nomecliente:
            type: string
            description: Nome Cliente
          ocr:
            type: boolean
            description: Captura automática de placa (OCR)
          dataliberacao:
            type: string
            format: date-time
            description: Data e hora da comunicação de liberação da carga pelo recinto (apenas na saída)
          paisdestino:
            type: string
            description: Pais destino da carga
          navioembarque:
            type: string
            description: Navio de embarque programado
  PosicaoConteiner:
    allOf:
      - $ref: '#/definitions/Evento'
      - type: object
        properties:
          numero:
            type: string
            description: Numero do conteiner
          placa:
            type: string
            description: Placa semireboque em caso de carregamento
          posicao:
            type: string
            description: Codigo que identifica a pilha no recinto
          altura:
            type: integer
            description: Altura do conteiner na pilha (0-chao até 6)
          emconferencia:
            type: boolean
            description: Posicao propria para desunitizacao ou conferencia
          solicitante:
            $ref: '#/definitions/Autoridade'
paths:
  /posicaoconteiner:
    post:
      operationId: app.posicaoconteiner
      parameters:
        - in: "body"
          name: "evento"
          description: "Controle de posição dos Contëineres no Pátio"
          required: true
          schema:
            $ref: "#/definitions/PosicaoConteiner"
      responses:
        200:
          description: "Evento incluido"
        405:
          description: "Evento invalido"
  /posicaoconteiner/{IDEvento}:
    get:
      operationId: app.get_posicaoconteiner
      parameters:
        - in: path
          name: IDEvento
          type: integer
          required: true
          description: "ID do Evento no Sistema original"
      responses:
        200:
          description: Evento Base
          schema:
            $ref: '#/definitions/PosicaoConteiner'
        400:
          description: ID inválido
        404:
          description: Evento com ID não encontrado para recinto atual.
        default:
          description: Erro inesperado
  /acessoveiculo:
    post:
      operationId: app.acessoveiculo
      parameters:
        - in: "body"
          name: "evento"
          description: "Controle de passagem em ponto de controle / entrada e saida de veiculos em area"
          required: true
          schema:
            $ref: "#/definitions/AcessoVeiculo"
      responses:
        200:
          description: "Evento incluido"
        405:
          description: "Evento invalido"
  /acessoveiculo/{IDEvento}:
    get:
      operationId: app.get_acessoveiculo
      parameters:
        - in: path
          name: IDEvento
          type: integer
          required: true
          description: "ID do Evento no Sistema original"
      responses:
        200:
          description: Evento Base
          schema:
            $ref: '#/definitions/AcessoVeiculo'
        400:
          description: ID inválido
        404:
          description: Evento com ID não encontrado para recinto atual.
        default:
          description: Erro inesperado

